---
sidebar: sidebar 
permalink: task-quick-start.html 
keywords: quick start, overview, deploying, getting started, get started, signing up, free trial 
summary: Die ersten Schritte mit dem Cloud Sync Service umfassen einige Schritte. 
---
= Schnellstart für Cloud Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Die ersten Schritte mit dem Cloud Sync Service umfassen einige Schritte.

[role="quick-margin-para"]
Sie sollten mit BlueXP angefangen haben, das die Anmeldung, die Einrichtung eines Kontos und die Bereitstellung eines Connectors sowie die Erstellung von Arbeitsumgebungen umfasst.

[role="quick-margin-para"]
Wenn Sie Synchronisierungsbeziehungen für eine der folgenden Elemente erstellen möchten, müssen Sie zunächst eine Arbeitsumgebung erstellen oder ermitteln:

* Amazon FSX für ONTAP
* Azure NetApp Dateien
* Cloud Volumes ONTAP
* ONTAP-Cluster vor Ort


[role="quick-margin-para"]
Für Cloud Volumes ONTAP, On-Premises-ONTAP-Cluster und Amazon FSX für ONTAP ist ein Connector erforderlich.

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-overview.html["Erfahren Sie, wie Sie BlueXP zum Einsatz bringen"^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Erfahren Sie mehr über Steckverbinder"^]


[role="quick-margin-para"]
Stellen Sie sicher, dass Ihre Quelle und Ihr Ziel unterstützt und eingerichtet werden. Die wichtigste Anforderung ist die Überprüfung der Konnektivität zwischen dem Daten-Broker-Gruppe und den Quell- und Zielstandorten.

* link:reference-supported-relationships.html["Unterstützte Beziehungen anzeigen"]
* link:reference-requirements.html["Bereiten Sie die Quelle und das Ziel vor"]


[role="quick-margin-para"]
Die NetApp Daten-Broker Software synchronisiert Daten von einer Quelle zu einem Ziel (dies wird als „_Sync Relationship_“ bezeichnet). Sie können den Data Broker in AWS, Azure, Google Cloud Platform oder vor Ort ausführen. Eine Datenmakler-Gruppe, die aus einem oder mehreren Datenmaklern besteht, benötigt eine ausgehende Internetverbindung über Port 443, damit sie mit dem Cloud Sync-Dienst kommunizieren und einige andere Dienste und Repositories kontaktieren kann. link:reference-networking.html#networking-endpoints["Zeigen Sie die Liste der Endpunkte an"].

[role="quick-margin-para"]
Cloud Sync führt Sie durch den Installationsprozess, wenn Sie eine Synchronisierungsbeziehung erstellen. Dann können Sie einen Daten-Broker in der Cloud bereitstellen oder ein Installationsskript für Ihren eigenen Linux-Host herunterladen.

* link:task-installing-aws.html["Überprüfen Sie die AWS-Installation"]
* link:task-installing-azure.html["Überprüfen Sie die Azure Installation"]
* link:task-installing-gcp.html["Lesen Sie die Google Cloud Installation"]
* link:task-installing-linux.html["Überprüfen Sie die Installation des Linux-Hosts"]


[role="quick-margin-para"]
Melden Sie sich bei an https://console.bluexp.netapp.com/["BlueXP"^]Klicken Sie auf *Sync* und ziehen Sie dann die Auswahl für die Quelle und das Ziel und legen Sie sie ab. Befolgen Sie die Anweisungen, um die Einrichtung abzuschließen. link:task-creating-relationships.html["Weitere Informationen ."].

[role="quick-margin-para"]
Abonnieren Sie AWS oder Azure, um nutzungsbasiert zu bezahlen oder jährlich zu zahlen. Oder erwerben Sie Lizenzen direkt von NetApp. Rufen Sie einfach die Seite Lizenzeinstellungen in Cloud Sync auf, um sie einzurichten. link:task-licensing.html["Weitere Informationen ."].
